services:
  readiness:
    build:
      context: .
      dockerfile: Dockerfile.readiness
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672/%2f}
      - BASELINE_SERVICE_URL=${BASELINE_SERVICE_URL:-http://baseline:8001}
    depends_on:
      - rabbitmq

  baseline:
    build:
      context: .
      dockerfile: Dockerfile.baseline
    ports:
      - "8001:8001"
    environment:
      - BASELINE_DATABASE_URL=${BASELINE_DATABASE_URL}
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672/%2f}
    volumes:
      - baseline_data:/data
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  physio-age:
    build:
      context: .
      dockerfile: Dockerfile.physio_age
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - readiness

volumes:
  baseline_data:


